version: '3'
services:
  scripts_py_template:
    image: developmentseed/scripts_py_template:v1
    build:
      context: .
      dockerfile: Dockerfile
    environment:
        - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
        - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    volumes:
        - ./:/mnt
    working_dir: /mnt
